### ISSUE TITLE
Mappers

### ISSUE THREAD

**Issue by RPallas92** [flipper83/protohipster#4]
Hola,

¿por qué pones los mappers en el dominio? ¿Se podrían poner en dataSource?

Gracias,
Saludos!

**Comment by flipper83** [comment]
Hola, este proyecto es bastante antiguo, así q hacia una cosa que era crear unos objetos intermedios de transporte q se llama boundaries. Hay un mapper del boundary al dominio y del boundary a la cama q sea. Es sobre ingeniera pero para aprender a desacoplar es bastante didáctico. No es necesario. Puedes mover los mappers fuera del dominó y ahorrarte ese objetos de transporte.

No se si me he explicado bien.

**Comment by RPallas92** [comment]
gracias, ahora me queda claro
